version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: csidb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prisma-postgres-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: prisma-postgres-api
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - type: bind
        source: ./backend
        target: /app

  react-ui:
    container_name: react-ui
    build: ./frontend
    command: npm start
    volumes:
      - './frontend:/app/'
      - '/frontend/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - prisma-postgres-api
    restart: on-failure
    stdin_open: true
    tty: true

volumes:
  postgres-data:
