version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: csidb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prisma-postgres-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: prisma-postgres-api
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - type: bind
        source: ./backend
        target: /app

volumes:
  postgres-data:
  pgadmin-data: